-- Add more metadata columns to sites table
ALTER TABLE sites
ADD COLUMN IF NOT EXISTS site_name VARCHAR(255) DEFAULT NULL AFTER site_number,
ADD COLUMN IF NOT EXISTS unit_type_id INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_ada BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vehicle_length INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS allow_web_booking BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_web_viewable BOOLEAN DEFAULT TRUE,
ADD INDEX idx_is_ada (is_ada),
ADD INDEX idx_vehicle_length (vehicle_length);

-- Add latitude/longitude to parks for map display
ALTER TABLE parks
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS address1 VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS state VARCHAR(2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS zip VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL;

-- Add more facility metadata
ALTER TABLE facilities
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS allow_web_booking BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS facility_type INT DEFAULT 1;



